language: node_js
sudo: required 
node_js : 
  - 5.0.0
install: 
  - npm install
cache: 
  directories: 
    - node_modules


script:
  - hexo cl
  - hexo g

after_script:
  - cd public 
  - git init
  - git config user.name "alexwan02"
  - git config user.email "alexwan0312@gmail.com"
  - git add -add .
  - git commit -m "travis ci auto build"
  - git push https://$Personal_access_tokens@github.com/alexwan02/alexwan02.github.io.git master
  
branches:
  only: 
    - hexo